package io.github.sudoitir.taraz.core.domain.transaction;

import java.util.Objects;
import java.util.UUID;

/** Identity of a ledger entry: a UUIDv7 generated by the domain's {@code IdGenerator} (ADR-0016). */
public record EntryId(UUID value) {

    public EntryId {
        Objects.requireNonNull(value, "value");
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
