package io.github.sudoitir.taraz.adapters.driven.persistence.transaction;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.jspecify.annotations.Nullable;

/**
 * Flat JPA entity for {@code ledger_transaction} (ADR-0015/0037). {@code id} is a surrogate UUIDv7 PK
 * (ADR-0016/0038, generated by the domain's {@code IdGenerator}); {@code externalId} is the client
 * {@code TransactionId} — the REST {@code Idempotency-Key} — kept distinct from the surrogate id so it
 * can never be confused with {@code processed_transaction}'s PK column of a similar name (ADR-0047).
 */
@Entity
@Table(name = "ledger_transaction")
@Getter
@Setter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class LedgerTransactionEntity {

    @Id
    @Column(nullable = false, updatable = false)
    private UUID id;

    @Column(nullable = false, updatable = false)
    private Instant occurredAt;

    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @Column(nullable = false, updatable = false, length = 16)
    private String type;

    @Column(nullable = false, updatable = false, length = 16)
    private String status;

    @Column(nullable = false, updatable = false, length = 64)
    private String externalId;

    @Column(updatable = false, length = 64)
    private @Nullable String compensatesExternalId;
}
