package io.github.sudoitir.taraz.adapters.driven.persistence.transaction;

import io.github.sudoitir.taraz.adapters.driven.persistence.common.MoneyEmbeddable;
import io.github.sudoitir.taraz.core.domain.transaction.LedgerEntry;
import io.github.sudoitir.taraz.core.domain.transaction.Transaction;
import java.time.Instant;
import java.util.UUID;
import org.mapstruct.Mapper;

/**
 * Domain → entity mapping for {@link Transaction}/{@link LedgerEntry} (ADR-0015/0031/0037). One
 * direction only — {@code TransactionRepository} has no load method (a transaction's persisted history
 * is audit trail, not something a command handler re-reads), so no entity-to-domain mapping exists here.
 */
@Mapper(componentModel = "spring")
public interface TransactionPersistenceMapper {

    /**
     * Maps the transaction's own fields onto its persisted row.
     *
     * @param surrogateId the UUIDv7 generated by the domain's {@code IdGenerator} for this row's PK
     *     (ADR-0016/0047) — distinct from {@code transaction.id()}, the client-supplied external id.
     */
    default LedgerTransactionEntity toEntity(Transaction transaction, UUID surrogateId, Instant createdAt) {
        LedgerTransactionEntity entity = new LedgerTransactionEntity();
        entity.setId(surrogateId);
        entity.setOccurredAt(transaction.occurredAt());
        entity.setCreatedAt(createdAt);
        entity.setType(transaction.type().name());
        entity.setStatus(transaction.status().name());
        entity.setExternalId(transaction.id().value());
        entity.setCompensatesExternalId(
                transaction.compensates().map(id -> id.value()).orElse(null));
        return entity;
    }

    default LedgerEntryEntity toEntity(LedgerEntry entry, UUID transactionSurrogateId, Instant createdAt) {
        LedgerEntryEntity entity = new LedgerEntryEntity();
        entity.setId(entry.id().value());
        entity.setCreatedAt(createdAt);
        entity.setTransactionId(transactionSurrogateId);
        entity.setAccountId(entry.accountId().value());
        entity.setDirection(entry.direction().name());
        entity.setAmount(new MoneyEmbeddable(entry.amount().minorUnits()));
        return entity;
    }
}
