package io.github.sudoitir.taraz.core.domain.account;

import java.util.Objects;
import java.util.UUID;

/** Identity of an account: a UUIDv7 generated by the domain's {@code IdGenerator} (ADR-0016). */
public record AccountId(UUID value) {

    public AccountId {
        Objects.requireNonNull(value, "value");
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
