package io.github.sudoitir.taraz.core.domain.account;

import io.github.sudoitir.taraz.core.domain.common.ErrorCode;
import io.github.sudoitir.taraz.core.domain.common.Result;
import java.util.Objects;
import java.util.UUID;
import org.jspecify.annotations.Nullable;

/**
 * Identity of an account: a UUIDv7 generated by the domain's {@code IdGenerator} (ADR-0016).
 *
 * <p>Ordering is unsigned lexicographic byte comparison of the underlying UUID — the same order
 * PostgreSQL's native {@code uuid} type uses — not {@link UUID#compareTo}, which compares the two
 * halves as <em>signed</em> longs. ADR-0026's deadlock-freedom depends on every caller (Java and SQL)
 * agreeing on one lock-acquisition order; the JDK's signed comparator would silently disagree with the
 * database for any pair of ids whose most-significant bit differs (ADR-0042).
 */
public record AccountId(UUID value) implements Comparable<AccountId> {

    public AccountId {
        Objects.requireNonNull(value, "value");
    }

    /** The validating route for client-supplied input. */
    public static Result<AccountId> of(@Nullable String value) {
        if (value == null || value.isBlank()) {
            return Result.failure(ErrorCode.INVALID_ACCOUNT_ID, "account id must not be blank");
        }
        try {
            return Result.success(new AccountId(UUID.fromString(value)));
        } catch (IllegalArgumentException e) {
            return Result.failure(ErrorCode.INVALID_ACCOUNT_ID, "account id must be a valid UUID: " + value);
        }
    }

    @Override
    public int compareTo(AccountId other) {
        int msb = Long.compareUnsigned(value.getMostSignificantBits(), other.value.getMostSignificantBits());
        return msb != 0
                ? msb
                : Long.compareUnsigned(value.getLeastSignificantBits(), other.value.getLeastSignificantBits());
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
